spring.application.name=event_booking_system

# ===================================================================
# Database Connection Settings
# ===================================================================
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_MoJaqV4dkA3U@ep-flat-sky-ao9hm4wk-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MoJaqV4dkA3U

# ===================================================================
# Server & JPA Settings
# ===================================================================
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MyBatis Settings
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
root-context.route=/api